parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"2tnM":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react");const t=(0,e.createContext)(["green",()=>{}]);var r=t;exports.default=r;
},{}],"qepC":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react-router-dom"),s=require("react/jsx-runtime");const r=({name:r,animal:t,breed:i,images:a,location:n,id:l})=>{let c="http://pets-images.dev-apis.com/pets/none.jpg";return a.length&&(c=a[0]),(0,s.jsxs)(e.Link,{to:`/details/${l}`,className:"pet",children:[(0,s.jsx)("div",{className:"image-container",children:(0,s.jsx)("img",{src:c,alt:r})}),(0,s.jsxs)("div",{className:"info",children:[(0,s.jsx)("h1",{children:r}),(0,s.jsx)("h2",{children:`${t} - ${i} - ${n}`})]})]})};var t=r;exports.default=t;
},{}],"r5l1":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=a(require("./Pet")),t=require("react/jsx-runtime");function a(e){return e&&e.__esModule?e:{default:e}}const r=({pets:a})=>(0,t.jsx)("div",{className:"search",children:a.length?a.map(a=>(0,t.jsx)(e.default,{animal:a.animal,name:a.name,breed:a.breed,images:a.images,location:`${a.city}, ${a.state}`,id:a.id},a.id)):(0,t.jsx)("h2",{children:"No pets Found"})});var s=r;exports.default=s;
},{"./Pet":"qepC"}],"/HkA":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=a;var e=require("react");const t={};function a(a){const[s,n]=(0,e.useState)([]),[o,r]=(0,e.useState)("unloaded");return(0,e.useEffect)(()=>{a?t[a]?n(t[a]):async function(){n([]),r("loading");const e=await fetch(`http://pets-v2.dev-apis.com/breeds?animal=${a}`),s=await e.json();t[a]=s.breeds||[],n(t[a]),r("loaded")}():n([])},[a]),[s,o]}
},{}],"n0tu":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),t=s(require("./ThemeContext")),a=s(require("./Results")),r=s(require("./useBreedList")),l=require("react/jsx-runtime");function s(e){return e&&e.__esModule?e:{default:e}}const n=["bird","cat","dog","horse","rabbit","turtle"],o=()=>{const[s,o]=(0,e.useState)(""),[i,u]=(0,e.useState)(""),[d,c]=(0,e.useState)(""),[h,x]=(0,e.useState)([]),[m]=(0,r.default)(i),[p,v]=(0,e.useContext)(t.default);async function j(){const e=await fetch(`http://pets-v2.dev-apis.com/pets?animal=${i}&location=${s}&breed=${d}`),t=await e.json();x(t.pets)}return(0,e.useEffect)(()=>{j()},[]),(0,l.jsxs)("div",{className:"search-params",children:[(0,l.jsxs)("form",{onSubmit:e=>{e.preventDefault(),j()},children:[(0,l.jsxs)("label",{htmlFor:"location",children:["Location",(0,l.jsx)("input",{id:"location",value:s,placeholder:"Location",onChange:e=>o(e.target.value)})]}),(0,l.jsxs)("label",{htmlFor:"animal",children:["Animal",(0,l.jsxs)("select",{id:"animal",value:i,onChange:e=>u(e.target.value),onBlur:e=>u(e.target.value),children:[(0,l.jsx)("option",{}),n.map(e=>(0,l.jsx)("option",{value:e,children:e},e))]})]}),(0,l.jsxs)("label",{htmlFor:"breed",children:["Breed",(0,l.jsxs)("select",{id:"breed",value:d,onChange:e=>c(e.target.value),onBlur:e=>c(e.target.value),children:[(0,l.jsx)("option",{}),m.map(e=>(0,l.jsx)("option",{value:e,children:e},e))]})]}),(0,l.jsxs)("label",{htmlFor:"theme",children:["Theme",(0,l.jsxs)("select",{id:"theme",value:p,onChange:e=>v(e.target.value),onBlur:e=>v(e.target.value),children:[(0,l.jsx)("option",{value:"darkblue",children:"Dark Blue"}),(0,l.jsx)("option",{value:"peru",children:"Peru"}),(0,l.jsx)("option",{value:"mediumorchid",children:"Medium Orchid"})]})]}),(0,l.jsx)("button",{style:{backgroundColor:p},children:"Submit"})]}),(0,l.jsx)(a.default,{pets:h})]})};var i=o;exports.default=i;
},{"./ThemeContext":"2tnM","./Results":"r5l1","./useBreedList":"/HkA"}],"Ztkr":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),t=require("react/jsx-runtime");function a(e,t,a){return t in e?Object.defineProperty(e,t,{value:a,enumerable:!0,configurable:!0,writable:!0}):e[t]=a,e}class s extends e.Component{constructor(...e){super(...e),a(this,"state",{active:0}),a(this,"handleIndexClick",e=>{this.setState({active:+e.target.dataset.index})})}render(){const{active:e}=this.state,{images:a}=this.props;return(0,t.jsxs)("div",{className:"carousel",children:[(0,t.jsx)("img",{src:a[e],alt:"animal"}),(0,t.jsx)("div",{className:"carousel-smaller",children:a.map((a,s)=>(0,t.jsx)("img",{src:a,"data-index":s,onClick:this.handleIndexClick,className:s===e?"active":"",alt:"animal thumbnail"},a))})]})}}a(s,"defaultProps",{images:["http://pets-images.dev-apis.com/pets/none.jpg"]});var i=s;exports.default=i;
},{}],"hVnS":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-router-dom"),t=require("react/jsx-runtime");function o(e,r,t){return r in e?Object.defineProperty(e,r,{value:t,enumerable:!0,configurable:!0,writable:!0}):e[r]=t,e}class s extends e.Component{constructor(...e){super(...e),o(this,"state",{hasError:!1})}static getDerivedStateFromError(e){return{hasError:!0}}componentDidCatch(e,r){console.error(e),setTimeout(()=>this.setState({redirect:!0}),5e3)}render(){return this.state.redirect?(0,t.jsx)(r.Redirect,{to:"/"}):this.state.hasError?(0,t.jsxs)("h2",{children:["Something went wrong ..",(0,t.jsx)(r.Link,{to:"/",children:" Go Home "}),"or wait 5 seconds to be redirected"]}):this.props.children}}var i=s;exports.default=i;
},{}],"KnKP":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("prettier"),r=require("react"),t=require("react-dom"),u=require("react/jsx-runtime");let c;const n=({children:e})=>{c=c||document.getElementById("modal");const n=(0,r.useRef)(null);return n.current||(n.current=document.createElement("div")),(0,r.useEffect)(()=>(c.appendChild(n.current),()=>c.removeChild(n.current)),[]),(0,t.createPortal)((0,u.jsx)("div",{children:e}),n.current)};var d=n;exports.default=d;
},{}],"C/Dc":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=u;var e=require("react"),t=require("react-router-dom"),s=a(require("./Carousel")),r=a(require("./ErrorBoundry")),i=a(require("./ThemeContext")),o=a(require("./Modal")),n=require("react/jsx-runtime");function a(e){return e&&e.__esModule?e:{default:e}}function d(e,t,s){return t in e?Object.defineProperty(e,t,{value:s,enumerable:!0,configurable:!0,writable:!0}):e[t]=s,e}class l extends e.Component{constructor(...e){super(...e),d(this,"state",{loading:!0,showModal:!1}),d(this,"toggleModal",()=>this.setState({showModal:!this.state.showModal})),d(this,"adopt",()=>window.location="http://bit.ly/pet-adopt")}async componentDidMount(){const e=await fetch(`http://pets-v2.dev-apis.com/pets?id=${this.props.match.params.id}`),t=await e.json();this.setState(Object.assign({loading:!1},t.pets[0]))}render(){if(this.state.loading)return(0,n.jsx)("h2",{children:"Loading..."});const{animal:e,breed:t,city:r,state:a,description:d,name:l,images:c,showModal:u}=this.state;if(!e)throw new Error("No animal found");return(0,n.jsxs)("div",{className:"details",children:[(0,n.jsx)(s.default,{images:c}),(0,n.jsxs)("div",{children:[(0,n.jsx)("h1",{children:l}),(0,n.jsx)("h2",{children:`${e} - ${t} - ${r}, ${a}`}),(0,n.jsx)(i.default.Consumer,{children:([e])=>(0,n.jsxs)("button",{onClick:this.toggleModal,style:{backgroundColor:e},children:["Adopt ",l]})}),(0,n.jsx)("p",{children:d}),u?(0,n.jsx)(o.default,{children:(0,n.jsxs)("div",{children:[(0,n.jsxs)("h2",{children:["Would you like to adopt ",l]}),(0,n.jsxs)("div",{className:"buttons",children:[(0,n.jsx)("button",{onClick:this.adopt,children:"Yes"}),(0,n.jsx)("button",{onClick:this.toggleModal,children:"No"})]})]})}):null]})]})}}const c=(0,t.withRouter)(l);function u(){return(0,n.jsx)(r.default,{children:(0,n.jsx)(c,{})})}
},{"./Carousel":"Ztkr","./ErrorBoundry":"hVnS","./ThemeContext":"2tnM","./Modal":"KnKP"}],"ffN9":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=a(require("react-dom")),r=require("react"),t=require("react-router-dom"),d=a(require("./SearchParams")),i=a(require("./Details")),s=a(require("./ThemeContext")),u=require("react/jsx-runtime");function a(e){return e&&e.__esModule?e:{default:e}}const l=()=>{const e=(0,r.useState)("darkblue");return(0,u.jsx)(r.StrictMode,{children:(0,u.jsx)(s.default.Provider,{value:e,children:(0,u.jsxs)("div",{children:[(0,u.jsx)("header",{children:(0,u.jsx)(t.Link,{to:"/",children:(0,u.jsx)("h1",{id:"my-brand",children:"Adopt Me!"})})}),(0,u.jsxs)(t.Switch,{children:[(0,u.jsx)(t.Route,{path:"/details/:id",children:(0,u.jsx)(i.default,{})}),(0,u.jsx)(t.Route,{path:"/",children:(0,u.jsx)(d.default,{})})]})]})})})};var c=l;exports.default=c;
},{"./SearchParams":"n0tu","./Details":"C/Dc","./ThemeContext":"2tnM"}],"Focm":[function(require,module,exports) {
"use strict";var e=n(require("express")),r=require("react-dom/server"),t=require("react-router-dom"),s=n(require("fs")),i=n(require("../src/app")),u=require("react-dom"),d=require("react/jsx-runtime");function n(e){return e&&e.__esModule?e:{default:e}}const o=process.env.PORT||3e3,a=s.default.readFileSync("dist/index.html").toString(),c=a.split("Not Rendered"),l=(0,e.default)();l.use("/dist",e.default.static("dist")),l.use((e,s)=>{s.write(c[0]);const u={},n=(0,d.jsx)(t.StaticRouter,{url:e.url,context:u,children:(0,d.jsx)(i.default,{})}),o=(0,r.renderToNodeStream)(n);o.pipe(s,{end:!1}),o.on("end",()=>{s.status(u.statusCode||200),s.write(c[1]),s.end()})}),console.log(`Listening on port ${o}`),l.listen(o);
},{"../src/app":"ffN9"}]},{},["Focm"], null)
//# sourceMappingURL=/index.js.map